ITEMS = [
    {
        "id": 1,
        "name": "Classic Leather Backpack",
        "price": "$89.00",
        "image_url": "static/images/backpack.png",
        "image_alt": "Tan leather backpack on a wooden surface",
        "lead": "A durable everyday carry built from full-grain leather with padded shoulder straps.",
        "description": "Roomy main compartment, front zip pocket, and weather-resistant lining for work or travel.",
    },
    {
        "id": 2,
        "name": "Wireless Noise-Canceling Headphones",
        "price": "$149.00",
        "image_url": "headphones.png",
        "image_alt": "Black over-ear wireless headphones",
        "lead": "Immersive sound with active noise cancellation and 30-hour battery life.",
        "description": "Soft memory-foam ear cups, Bluetooth 5.3, and a fold-flat design for easy packing.",
    },
    {
        "id": 3,
        "name": "Stainless Steel Water Bottle",
        "price": "$32.00",
        "image_url": "water_bottle.png",
        "image_alt": "Insulated steel water bottle outdoors",
        "lead": "Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12.",
        "description": "BPA-free, leak-proof cap, and a powder-coated finish that resists dents and scratches.",
    },
    {
        "id": 4,
        "name": "Ceramic Pour-Over Coffee Set",
        "price": "$54.00",
        "image_url": "coffee.png",
        "image_alt": "Pour-over coffee dripping into a mug",
        "lead": "Brew café-quality coffee at home with a handcrafted dripper and carafe.",
        "description": "Includes ceramic dripper, glass carafe, and 100 paper filters for smooth, balanced cups.",
    },
    {
        "id": 5,
        "name": "Minimalist Desk Lamp",
        "price": "$68.00",
        "image_url": "https://images.unsplash.com/photo-1507473885762-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Modern desk lamp on a home office desk",
        "lead": "Adjustable LED lamp with warm-to-cool color temperature control.",
        "description": "Touch dimmer, flexible gooseneck arm, and a weighted base for stable placement.",
    },
    {
        "id": 6,
        "name": "Organic Cotton T-Shirt",
        "price": "$28.00",
        "image_url": "shirt.png",
        "image_alt": "Plain white cotton t-shirt folded neatly",
        "lead": "Soft, breathable tee made from 100% organic cotton with a relaxed fit.",
        "description": "Pre-shrunk fabric, reinforced neckline, and available in classic neutral tones.",
    },
    {
        "id": 7,
        "name": "Running Shoes",
        "price": "$119.00",
        "image_url": "shoes.png",
        "image_alt": "Red athletic running shoe",
        "lead": "Lightweight trainers with responsive cushioning for road and track runs.",
        "description": "Breathable mesh upper, grippy rubber outsole, and arch support for all-day comfort.",
    },
    {
        "id": 8,
        "name": "Smart Fitness Watch",
        "price": "$199.00",
        "image_url": "watch.png",
        "image_alt": "White smartwatch with a clean watch face",
        "lead": "Track workouts, heart rate, sleep, and notifications from your wrist.",
        "description": "Water-resistant to 50m, GPS built in, and a week of battery on a single charge.",
    },
    {
        "id": 9,
        "name": "Mechanical Keyboard",
        "price": "$129.00",
        "image_url": "keyboard.png",
        "image_alt": "Mechanical keyboard with RGB backlighting",
        "lead": "Tactile switches and aluminum frame built for typing and gaming.",
        "description": "Hot-swappable keys, USB-C connection, and programmable RGB lighting profiles.",
    },
    {
        "id": 10,
        "name": "Polarized Sunglasses",
        "price": "$75.00",
        "image_url": "https://images.unsplash.com/photo-1572635196233-8f0f758081ac?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Stylish sunglasses on a bright background",
        "lead": "UV400 protection with glare-reducing polarized lenses.",
        "description": "Lightweight acetate frames, scratch-resistant coating, and a hard case included.",
    },
    {
        "id": 11,
        "name": "Scented Soy Candle",
        "price": "$24.00",
        "image_url": "https://images.unsplash.com/photo-1602571429218-7b95610e6907?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Lit candle in a glass jar on a table",
        "lead": "Hand-poured soy wax candle with a 45-hour burn time.",
        "description": "Notes of cedar, vanilla, and bergamot in a reusable amber glass vessel.",
    },
    {
        "id": 12,
        "name": "Hardcover Notebook",
        "price": "$18.00",
        "image_url": "https://images.unsplash.com/photo-1531346878377-a5be208ad327?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Open notebook with pen on a desk",
        "lead": "240 pages of acid-free paper with a lay-flat binding.",
        "description": "Dotted grid pages, elastic closure, and a ribbon bookmark for daily journaling.",
    },
    {
        "id": 13,
        "name": "Indoor Succulent Planter",
        "price": "$36.00",
        "image_url": "https://images.unsplash.com/photo-1459411552885-d0b301d5a522?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Small succulent plant in a ceramic pot",
        "lead": "Low-maintenance desk plant in a matte ceramic pot.",
        "description": "Includes drainage tray, pre-mixed soil, and care instructions for bright indirect light.",
    },
    {
        "id": 14,
        "name": "Cast Iron Skillet",
        "price": "$58.00",
        "image_url": "https://images.unsplash.com/photo-1615874957797-f11e874858c8?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Cast iron skillet on a stovetop",
        "lead": "Pre-seasoned 10-inch skillet for stovetop, oven, and campfire cooking.",
        "description": "Even heat retention, natural non-stick patina, and a helper handle for easy lifting.",
    },
    {
        "id": 15,
        "name": "Yoga Mat",
        "price": "$42.00",
        "image_url": "https://images.unsplash.com/photo-1601925260368-ae2f83b8b118?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Rolled yoga mat on a studio floor",
        "lead": "Extra-thick mat with non-slip texture for yoga and pilates.",
        "description": "Eco-friendly TPE material, alignment markers, and a carrying strap included.",
    },
    {
        "id": 16,
        "name": "Portable Bluetooth Speaker",
        "price": "$79.00",
        "image_url": "https://images.unsplash.com/photo-1545454671052-406a5215700a?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Compact bluetooth speaker on a shelf",
        "lead": "Room-filling sound in a rugged, water-resistant body.",
        "description": "12-hour playtime, stereo pairing, and a built-in microphone for hands-free calls.",
    },
    {
        "id": 17,
        "name": "Wool Throw Blanket",
        "price": "$95.00",
        "image_url": "blanket.png",
        "image_alt": "Cozy wool blanket draped over a sofa",
        "lead": "Soft merino wool blend for warmth without overheating.",
        "description": "Fringed edges, machine-washable on gentle cycle, and sized for sofa or bed layering.",
    },
    {
        "id": 18,
        "name": "Stainless Chef Knife",
        "price": "$110.00",
        "image_url": "https://images.unsplash.com/photo-1593618998168-c4dd99822e96?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Professional chef knife on a cutting board",
        "lead": "8-inch forged blade with ergonomic handle for precision prep.",
        "description": "High-carbon stainless steel, full tang construction, and a protective blade cover.",
    },
    {
        "id": 19,
        "name": "Leather Wallet",
        "price": "$45.00",
        "image_url": "https://images.unsplash.com/photo-1627123424574-7a71a33f9e0e?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Brown leather bifold wallet",
        "lead": "Slim bifold with RFID-blocking lining and six card slots.",
        "description": "Hand-stitched edges, cash compartment, and a gift-ready presentation box.",
    },
    {
        "id": 20,
        "name": "Ceramic Dinner Plate Set",
        "price": "$72.00",
        "image_url": "https://images.unsplash.com/photo-1578507061120-f99fb2c04f20?w=800&auto=format&fit=crop&q=80",
        "image_alt": "Stack of white ceramic dinner plates",
        "lead": "Set of four stoneware plates with a speckled glaze finish.",
        "description": "Microwave and dishwasher safe, chip-resistant rims, and stackable for compact storage.",
    },
]
