ITEMS = [
    {
        "id": 1,
        "name": "Classic Leather Backpack",
        "category": "Accessories",
        "price": "$89.00",
        "image_url": "backpack.png",
        "image_alt": "Tan leather backpack on a wooden surface",
        "lead": "A durable everyday carry built from full-grain leather with padded shoulder straps.",
        "description": "Roomy main compartment, front zip pocket, and weather-resistant lining for work or travel.",
    },
    {
        "id": 2,
        "name": "Wireless Noise-Canceling Headphones",
        "category": "Electronics",
        "price": "$149.00",
        "image_url": "headphones.png",
        "image_alt": "Black over-ear wireless headphones",
        "lead": "Immersive sound with active noise cancellation and 30-hour battery life.",
        "description": "Soft memory-foam ear cups, Bluetooth 5.3, and a fold-flat design for easy packing.",
    },
    {
        "id": 3,
        "name": "Stainless Steel Water Bottle",
        "category": "Kitchen & Drinkware",
        "price": "$32.00",
        "image_url": "water_bottle.png",
        "image_alt": "Insulated steel water bottle outdoors",
        "lead": "Double-wall vacuum insulation keeps drinks cold for 24 hours or hot for 12.",
        "description": "BPA-free, leak-proof cap, and a powder-coated finish that resists dents and scratches.",
    },
    {
        "id": 4,
        "name": "Ceramic Pour-Over Coffee Set",
        "category": "Kitchen & Drinkware",
        "price": "$54.00",
        "image_url": "coffee.png",
        "image_alt": "Pour-over coffee dripping into a mug",
        "lead": "Brew café-quality coffee at home with a handcrafted dripper and carafe.",
        "description": "Includes ceramic dripper, glass carafe, and 100 paper filters for smooth, balanced cups.",
    },
    {
        "id": 5,
        "name": "Minimalist Desk Lamp",
        "category": "Home & Office",
        "price": "$68.00",
        "image_url": "lamp.png",
        "image_alt": "Modern desk lamp on a home office desk",
        "lead": "Adjustable LED lamp with warm-to-cool color temperature control.",
        "description": "Touch dimmer, flexible gooseneck arm, and a weighted base for stable placement.",
    },
    {
        "id": 6,
        "name": "Organic Cotton T-Shirt",
        "category": "Apparel",
        "price": "$28.00",
        "image_url": "shirt.png",
        "image_alt": "Plain white cotton t-shirt folded neatly",
        "lead": "Soft, breathable tee made from 100% organic cotton with a relaxed fit.",
        "description": "Pre-shrunk fabric, reinforced neckline, and available in classic neutral tones.",
    },
    {
        "id": 7,
        "name": "Running Shoes",
        "category": "Apparel",
        "price": "$119.00",
        "image_url": "shoes.png",
        "image_alt": "Red athletic running shoe",
        "lead": "Lightweight trainers with responsive cushioning for road and track runs.",
        "description": "Breathable mesh upper, grippy rubber outsole, and arch support for all-day comfort.",
    },
    {
        "id": 8,
        "name": "Smart Fitness Watch",
        "category": "Electronics",
        "price": "$199.00",
        "image_url": "watch.png",
        "image_alt": "White smartwatch with a clean watch face",
        "lead": "Track workouts, heart rate, sleep, and notifications from your wrist.",
        "description": "Water-resistant to 50m, GPS built in, and a week of battery on a single charge.",
    },
    {
        "id": 9,
        "name": "Mechanical Keyboard",
        "category": "Electronics",
        "price": "$129.00",
        "image_url": "keyboard.png",
        "image_alt": "Mechanical keyboard with RGB backlighting",
        "lead": "Tactile switches and aluminum frame built for typing and gaming.",
        "description": "Hot-swappable keys, USB-C connection, and programmable RGB lighting profiles.",
    },
    {
        "id": 10,
        "name": "Polarized Sunglasses",
        "category": "Accessories",
        "price": "$75.00",
        "image_url": "sunglasses.png",
        "image_alt": "Stylish sunglasses on a bright background",
        "lead": "UV400 protection with glare-reducing polarized lenses.",
        "description": "Lightweight acetate frames, scratch-resistant coating, and a hard case included.",
    },
    {
        "id": 11,
        "name": "Scented Soy Candle",
        "category": "Home & Office",
        "price": "$24.00",
        "image_url": "candle.png",
        "image_alt": "Lit candle in a glass jar on a table",
        "lead": "Hand-poured soy wax candle with a 45-hour burn time.",
        "description": "Notes of cedar, vanilla, and bergamot in a reusable amber glass vessel.",
    },
    {
        "id": 12,
        "name": "Hardcover Notebook",
        "category": "Home & Office",
        "price": "$18.00",
        "image_url": "notebook.png",
        "image_alt": "Open notebook with pen on a desk",
        "lead": "240 pages of acid-free paper with a lay-flat binding.",
        "description": "Dotted grid pages, elastic closure, and a ribbon bookmark for daily journaling.",
    },
    {
        "id": 13,
        "name": "Indoor Succulent Planter",
        "category": "Home & Office",
        "price": "$36.00",
        "image_url": "planter.png",
        "image_alt": "Small succulent plant in a ceramic pot",
        "lead": "Low-maintenance desk plant in a matte ceramic pot.",
        "description": "Includes drainage tray, pre-mixed soil, and care instructions for bright indirect light.",
    },
    {
        "id": 14,
        "name": "Cast Iron Skillet",
        "category": "Kitchen & Drinkware",
        "price": "$58.00",
        "image_url": "skillet.png",
        "image_alt": "Cast iron skillet on a stovetop",
        "lead": "Pre-seasoned 10-inch skillet for stovetop, oven, and campfire cooking.",
        "description": "Even heat retention, natural non-stick patina, and a helper handle for easy lifting.",
    },
    {
        "id": 15,
        "name": "Yoga Mat",
        "category": "Fitness",
        "price": "$42.00",
        "image_url": "yoga.png",
        "image_alt": "Rolled yoga mat on a studio floor",
        "lead": "Extra-thick mat with non-slip texture for yoga and pilates.",
        "description": "Eco-friendly TPE material, alignment markers, and a carrying strap included.",
    },
    {
        "id": 16,
        "name": "Portable Bluetooth Speaker",
        "category": "Electronics",
        "price": "$79.00",
        "image_url": "speaker.png",
        "image_alt": "Compact bluetooth speaker on a shelf",
        "lead": "Room-filling sound in a rugged, water-resistant body.",
        "description": "12-hour playtime, stereo pairing, and a built-in microphone for hands-free calls.",
    },
    {
        "id": 17,
        "name": "Wool Throw Blanket",
        "category": "Home & Office",
        "price": "$95.00",
        "image_url": "blanket.png",
        "image_alt": "Cozy wool blanket draped over a sofa",
        "lead": "Soft merino wool blend for warmth without overheating.",
        "description": "Fringed edges, machine-washable on gentle cycle, and sized for sofa or bed layering.",
    },
    {
        "id": 18,
        "name": "Stainless Chef Knife",
        "category": "Kitchen & Drinkware",
        "price": "$110.00",
        "image_url": "knife.png",
        "image_alt": "Professional chef knife on a cutting board",
        "lead": "8-inch forged blade with ergonomic handle for precision prep.",
        "description": "High-carbon stainless steel, full tang construction, and a protective blade cover.",
    },
    {
        "id": 19,
        "name": "Leather Wallet",
        "category": "Accessories",
        "price": "$45.00",
        "image_url": "wallet.png",
        "image_alt": "Brown leather bifold wallet",
        "lead": "Slim bifold with RFID-blocking lining and six card slots.",
        "description": "Hand-stitched edges, cash compartment, and a gift-ready presentation box.",
    },
    {
        "id": 20,
        "name": "Ceramic Dinner Plate Set",
        "category": "Kitchen & Drinkware",
        "price": "$72.00",
        "image_url": "plates.png",
        "image_alt": "Stack of white ceramic dinner plates",
        "lead": "Set of four stoneware plates with a speckled glaze finish.",
        "description": "Microwave and dishwasher safe, chip-resistant rims, and stackable for compact storage.",
    },
    {
        "id": 21,
        "name": "Insulated Travel Mug",
        "category": "Kitchen & Drinkware",
        "price": "$38.00",
        "image_url": "travel_mug.png",
        "image_alt": "Stainless travel mug on a desk",
        "lead": "Double-wall insulation keeps drinks hot or cold for hours on the go.",
        "description": "Leak-proof lid with a slide-lock opening and a fit that works in most car cup holders.",
    },
    {
        "id": 22,
        "name": "Bluetooth Earbuds",
        "category": "Electronics",
        "price": "$89.00",
        "image_url": "earbuds.png",
        "image_alt": "White wireless earbuds in charging case",
        "lead": "Compact true wireless earbuds with crisp audio and a pocket-sized charging case.",
        "description": "Touch controls, active noise reduction, and up to 24 hours of total battery with the case.",
    },
    {
        "id": 23,
        "name": "Canvas Tote Bag",
        "category": "Accessories",
        "price": "$34.00",
        "image_url": "tote_bag.png",
        "image_alt": "Natural canvas tote bag with handles",
        "lead": "Spacious everyday tote made from heavy-duty cotton canvas.",
        "description": "Reinforced handles, interior pocket, and machine-washable fabric for errands or the beach.",
    },
    {
        "id": 24,
        "name": "Desk Organizer Set",
        "category": "Home & Office",
        "price": "$46.00",
        "image_url": "desk_organizer.png",
        "image_alt": "Bamboo desk organizer with compartments",
        "lead": "Bamboo desktop organizer with slots for pens, notes, and small accessories.",
        "description": "Modular trays keep supplies tidy and add a clean natural look to any workspace.",
    },
    {
        "id": 25,
        "name": "Weighted Throw Pillow",
        "category": "Home & Office",
        "price": "$29.00",
        "image_url": "throw_pillow.png",
        "image_alt": "Decorative pillow on a sofa",
        "lead": "Soft square accent pillow with a removable cover and plush fill.",
        "description": "Hidden zipper, machine-washable cover, and neutral tone that pairs with living room or bedroom decor.",
    },
    {
        "id": 26,
        "name": "Stainless Lunch Box",
        "category": "Kitchen & Drinkware",
        "price": "$42.00",
        "image_url": "lunch_box.png",
        "image_alt": "Metal lunch container with lid",
        "lead": "Three-compartment lunch box with a secure snap lid for meal prep.",
        "description": "BPA-free, dishwasher-safe design keeps food separated and fresh until lunchtime.",
    },
    {
        "id": 27,
        "name": "Resistance Band Set",
        "category": "Fitness",
        "price": "$26.00",
        "image_url": "resistance_bands.png",
        "image_alt": "Colorful exercise resistance bands",
        "lead": "Set of five latex bands with varying resistance levels for home workouts.",
        "description": "Includes door anchor, handles, and a carry pouch for strength training and mobility exercises.",
    },
    {
        "id": 28,
        "name": "Glass Food Storage Set",
        "category": "Kitchen & Drinkware",
        "price": "$58.00",
        "image_url": "food_storage.png",
        "image_alt": "Stack of glass containers with lids",
        "lead": "Four-piece borosilicate glass container set with airtight lids.",
        "description": "Oven, microwave, and freezer safe with snap-lock lids that resist leaks and stains.",
    },
    {
        "id": 29,
        "name": "Rechargeable Desk Fan",
        "category": "Home & Office",
        "price": "$52.00",
        "image_url": "desk_fan.png",
        "image_alt": "Small USB desk fan on a table",
        "lead": "Quiet USB-powered desk fan with adjustable tilt and two speed settings.",
        "description": "Compact design ideal for home office or bedside use with low-noise operation.",
    },
    {
        "id": 30,
        "name": "Leather Belt",
        "category": "Apparel",
        "price": "$55.00",
        "image_url": "leather_belt.png",
        "image_alt": "Brown leather belt coiled on white background",
        "lead": "Full-grain leather belt with a brushed metal buckle and classic stitching.",
        "description": "Available in standard sizes with a durable finish suited for casual or business wear.",
    },
    {
        "id": 31,
        "name": "Portable Bluetooth Speaker",
        "category": "Electronics",
        "price": "$79.00",
        "image_url": "headphones.png",
        "image_alt": "Compact black portable speaker on a desk",
        "lead": "Room-filling sound in a pocket-sized speaker with 12-hour battery life.",
        "description": "Bluetooth 5.0, IPX5 water resistance, and a built-in microphone for calls.",
    },
]
